// End-to-end tests for the ingest paths the bundled samples can exercise:
// the 3D NIfTI sample under the default and a forced pixel budget, the 3D
// OME-Zarr sample (sharded Zarr v3 stores), the URL fields with the 2D
// OME-Zarr directory stores, the file pickers with generated MetaImages,
// and the pair check with the swap button. Assertions are
// read from the app state (`window.__demo.state`, published by src/main.ts)
// and the splash's pending slots (`window.__demo.splash`) rather than from
// rendered text wherever the state carries the fact; only the danger callout
// and the slot summaries are checked as the user sees them. The OZX and
// OME-TIFF round trips live in test/outputs.spec.ts, which downloads their
// fixtures first; the page helpers both files use are in test/helpers.ts.
import { expect, test as base, type Locator, type Page } from '@playwright/test'

import { BUDGET_QUERY_PARAM, PIXEL_BUDGET_BYTES } from '../src/io/scale-select'
import type { SlotRole } from '../src/ui/splash-slots'
import {
  LOAD_TIMEOUT_3D,
  MNI_FIXED,
  MNI_MOVING,
  MNI_SAMPLE_BUTTON,
  SAMPLES_DIR,
  TAILBUD_2D_FIXED,
  TAILBUD_2D_MOVING,
  TAILBUD_3D_FIXED,
  TAILBUD_3D_MOVING,
  TAILBUD_3D_SAMPLE_BUTTON,
  collectPageErrors,
  holdRegistration,
  imageFacts,
  isDisabled,
  loadSample,
  splashDialog,
  start,
  syntheticMetaImage,
  volumeCount,
  waitForSlot,
  type FilePayload,
} from './helpers'

/** Pixel budget, in MiB, small enough to force the 3D sample down a pyramid level. */
const SMALL_BUDGET_MIB = 4
const SMALL_BUDGET_BYTES = SMALL_BUDGET_MIB * 1024 * 1024

/** Every test fails if the page threw an uncaught error. */
const test = base.extend<{ pageErrors: string[] }>({
  pageErrors: [
    async ({ page }, use) => {
      const errors: string[] = []
      collectPageErrors(page, errors)
      await use(errors)
      expect(errors, 'the page should not throw').toEqual([])
    },
    { auto: true },
  ],
})

/** Names of the pair the app store holds; undefined entries for empty slots. */
function storeNames(page: Page): Promise<{ fixed?: string; moving?: string }> {
  return page.evaluate(() => {
    const state = window.__demo?.state?.state
    return { fixed: state?.fixed?.name, moving: state?.moving?.name }
  })
}

/** The value cell of one summary row under a splash slot. */
function summaryValue(page: Page, role: SlotRole, field: string): Locator {
  return page.locator(`#${role}-summary .summary-row[data-field="${field}"] dd`)
}

/** Type `url` into the slot's URL field and load it. */
async function loadUrl(page: Page, role: SlotRole, url: string, submit: 'button' | 'enter'): Promise<void> {
  // `fill` must target the input inside the wa-input's shadow root; the
  // host element is not a form control.
  const field = page.locator(`#${role}-url input`)
  await field.fill(url)
  if (submit === 'enter') {
    await field.press('Enter')
  } else {
    const load = page.locator(`#${role}-url-load`)
    await expect.poll(() => isDisabled(load), { message: 'typing a URL should enable Load' }).toBe(false)
    await load.click()
  }
}

/** Pick `file` (a name in the samples directory, or generated bytes) through the slot's hidden file input. */
async function pickFile(page: Page, role: SlotRole, file: string | FilePayload): Promise<void> {
  await page.locator(`#${role}-file`).setInputFiles(typeof file === 'string' ? `${SAMPLES_DIR}${file}` : file)
}

/** A 2D pair for the file pickers: the same disk, shifted between the two. */
const PICKED_FIXED = syntheticMetaImage('disk-fixed.mha')
const PICKED_MOVING = syntheticMetaImage('disk-moving.mha', { cx: 54, cy: 36 })

test.describe('3D MNI sample', () => {
  test('loads both volumes at full resolution under the default budget', async ({ page }) => {
    await page.goto('./')
    await loadSample(page, MNI_SAMPLE_BUTTON, LOAD_TIMEOUT_3D)

    const fixed = await imageFacts(page, 'store', 'fixed')
    const moving = await imageFacts(page, 'store', 'moving')
    expect(fixed?.name).toBe(MNI_FIXED)
    expect(moving?.name).toBe(MNI_MOVING)
    for (const image of [fixed, moving]) {
      expect(image?.dimension).toBe(3)
      expect(image?.size).toHaveLength(3)
      expect(image?.kind).toBe('itk')
      expect(image?.format).toBe('ITK')
      expect(image?.scaleIndex).toBe(0)
      expect(image?.budgetBytes).toBe(PIXEL_BUDGET_BYTES)
      expect(image?.registrationBytes).toBeGreaterThan(SMALL_BUDGET_BYTES)
      expect(image?.registrationBytes).toBeLessThanOrEqual(PIXEL_BUDGET_BYTES)
    }
  })

  test(`downsamples both volumes under ?${BUDGET_QUERY_PARAM}=${SMALL_BUDGET_MIB}`, async ({ page }) => {
    await page.goto(`./?${BUDGET_QUERY_PARAM}=${SMALL_BUDGET_MIB}`)
    await loadSample(page, MNI_SAMPLE_BUTTON, LOAD_TIMEOUT_3D)

    const fixed = await imageFacts(page, 'store', 'fixed')
    const moving = await imageFacts(page, 'store', 'moving')
    expect(fixed?.name).toBe(MNI_FIXED)
    expect(moving?.name).toBe(MNI_MOVING)
    for (const image of [fixed, moving]) {
      // Both templates exceed 4 MiB at full resolution, so each needs at
      // least one extra pyramid level and registers from a coarser one.
      expect(image?.dimension).toBe(3)
      expect(image?.budgetBytes).toBe(SMALL_BUDGET_BYTES)
      expect(image?.levels).toBeGreaterThanOrEqual(2)
      expect(image?.scaleIndex).toBeGreaterThanOrEqual(1)
      expect(image?.registrationBytes).toBeLessThanOrEqual(SMALL_BUDGET_BYTES)
    }
  })
})

test.describe('3D zebrafish tailbud sample', () => {
  test('loads both sharded OME-Zarr z-stacks at full resolution under the default budget', async ({ page }) => {
    await holdRegistration(page)
    await page.goto('./')
    await loadSample(page, TAILBUD_3D_SAMPLE_BUTTON, LOAD_TIMEOUT_3D)

    for (const [role, name] of [
      ['fixed', TAILBUD_3D_FIXED],
      ['moving', TAILBUD_3D_MOVING],
    ] as const) {
      expect(await imageFacts(page, 'store', role)).toMatchObject({
        name,
        kind: 'ome-zarr-url',
        format: 'OME-Zarr',
        dimension: 3,
        size: [333, 333, 201],
        scaleIndex: 0,
        levels: 2,
        // uint16 voxels, just inside the 50 MB default budget.
        registrationBytes: 333 * 333 * 201 * 2,
        budgetBytes: PIXEL_BUDGET_BYTES,
      })
    }
  })
})

test('loads the tailbud planes from the URL fields as OME-Zarr stores, by the Load button and by Enter', async ({
  page,
  baseURL,
}) => {
  await page.goto('./')
  await expect(splashDialog(page)).toBeVisible()
  const startButton = page.locator('#start-registration-inputs')
  expect(await isDisabled(startButton)).toBe(true)

  // The dev server's own copies of the bundled samples, read as directory stores.
  await loadUrl(page, 'fixed', new URL(`samples/${TAILBUD_2D_FIXED}`, baseURL).href, 'button')
  await waitForSlot(page, 'fixed', TAILBUD_2D_FIXED)
  expect(await isDisabled(startButton), 'one slot is not enough to start').toBe(true)
  expect(await storeNames(page), 'a pending slot must not reach the store').toEqual({})

  await loadUrl(page, 'moving', new URL(`samples/${TAILBUD_2D_MOVING}`, baseURL).href, 'enter')
  await waitForSlot(page, 'moving', TAILBUD_2D_MOVING)
  await expect(page.locator('#splash-error')).toBeHidden()

  await start(page)
  const fixed = await imageFacts(page, 'store', 'fixed')
  const moving = await imageFacts(page, 'store', 'moving')
  const plane = { kind: 'ome-zarr-url', format: 'OME-Zarr', dimension: 2, size: [333, 333], scaleIndex: 0, levels: 2 }
  expect(fixed).toMatchObject({ name: TAILBUD_2D_FIXED, ...plane })
  expect(moving).toMatchObject({ name: TAILBUD_2D_MOVING, ...plane })
  await expect.poll(() => volumeCount(page, 'inputs-fixed')).toBe(1)
  await expect.poll(() => volumeCount(page, 'inputs-moving')).toBe(1)
})

test('loads a 2D pair from the file pickers', async ({ page }) => {
  await page.goto('./')
  await expect(splashDialog(page)).toBeVisible()

  await pickFile(page, 'fixed', PICKED_FIXED)
  await waitForSlot(page, 'fixed', PICKED_FIXED.name)
  await pickFile(page, 'moving', PICKED_MOVING)
  await waitForSlot(page, 'moving', PICKED_MOVING.name)
  await expect(page.locator('#splash-error')).toBeHidden()

  // The input is reset after each pick so the same file can be chosen again.
  expect(await page.locator('#fixed-file').evaluate((input: HTMLInputElement) => input.value)).toBe('')

  await start(page)
  const fixed = await imageFacts(page, 'store', 'fixed')
  const moving = await imageFacts(page, 'store', 'moving')
  const picked = { kind: 'itk', format: 'ITK', dimension: 2, size: [96, 80], scaleIndex: 0 }
  expect(fixed).toMatchObject({ name: PICKED_FIXED.name, ...picked })
  expect(moving).toMatchObject({ name: PICKED_MOVING.name, ...picked })
  expect(fixed?.budgetBytes).toBe(PIXEL_BUDGET_BYTES)
  await expect.poll(() => volumeCount(page, 'inputs-fixed')).toBe(1)
  await expect.poll(() => volumeCount(page, 'inputs-moving')).toBe(1)
})

test('rejects a 2D fixed with a 3D moving image, keeps the dialog open, and swaps the slots', async ({ page }) => {
  await page.goto('./')
  await expect(splashDialog(page)).toBeVisible()
  const callout = page.locator('#splash-error')
  const startButton = page.locator('#start-registration-inputs')
  const swap = page.locator('#swap-images')

  await pickFile(page, 'fixed', PICKED_FIXED)
  await waitForSlot(page, 'fixed', PICKED_FIXED.name)
  await expect(callout).toBeHidden()

  await pickFile(page, 'moving', MNI_MOVING)
  await waitForSlot(page, 'moving', MNI_MOVING, LOAD_TIMEOUT_3D)

  await test.step('the pair check shows in the danger callout as soon as both slots are filled', async () => {
    expect(await imageFacts(page, 'splash', 'fixed')).toMatchObject({ name: PICKED_FIXED.name, dimension: 2 })
    expect(await imageFacts(page, 'splash', 'moving')).toMatchObject({ name: MNI_MOVING, dimension: 3 })

    await expect(callout).toBeVisible()
    await expect(callout).toHaveAttribute('variant', 'danger')
    await expect(callout).toContainText('dimension')
    await expect(callout).toContainText(`${PICKED_FIXED.name} is 2D but the moving image ${MNI_MOVING} is 3D`)

    await expect(splashDialog(page)).toBeVisible()
    expect(await isDisabled(startButton), 'Start must stay disabled for a mismatched pair').toBe(true)
    expect(await storeNames(page), 'the app must not receive the pair').toEqual({})
  })

  await test.step('swapping exchanges the slots, their summaries, and the message', async () => {
    expect(await isDisabled(swap)).toBe(false)
    await expect(summaryValue(page, 'fixed', 'name')).toHaveText(PICKED_FIXED.name)
    await expect(summaryValue(page, 'moving', 'name')).toHaveText(MNI_MOVING)

    await swap.click()

    await expect.poll(async () => (await imageFacts(page, 'splash', 'fixed'))?.name).toBe(MNI_MOVING)
    expect(await imageFacts(page, 'splash', 'fixed')).toMatchObject({ name: MNI_MOVING, dimension: 3 })
    expect(await imageFacts(page, 'splash', 'moving')).toMatchObject({ name: PICKED_FIXED.name, dimension: 2 })
    await expect(summaryValue(page, 'fixed', 'name')).toHaveText(MNI_MOVING)
    await expect(summaryValue(page, 'fixed', 'dimension')).toHaveText('3D')
    await expect(summaryValue(page, 'moving', 'name')).toHaveText(PICKED_FIXED.name)
    await expect(summaryValue(page, 'moving', 'dimension')).toHaveText('2D')

    // Still mismatched, now the other way round.
    await expect(callout).toBeVisible()
    await expect(callout).toContainText(`${MNI_MOVING} is 3D but the moving image ${PICKED_FIXED.name} is 2D`)
    await expect(splashDialog(page)).toBeVisible()
    expect(await isDisabled(startButton)).toBe(true)
    expect(await storeNames(page)).toEqual({})
  })

  await test.step('replacing the 3D image with a 2D moving image clears the check', async () => {
    await swap.click()
    await expect.poll(async () => (await imageFacts(page, 'splash', 'fixed'))?.name).toBe(PICKED_FIXED.name)
    await pickFile(page, 'moving', PICKED_MOVING)
    await waitForSlot(page, 'moving', PICKED_MOVING.name)
    await expect(callout).toBeHidden()
    await expect.poll(() => isDisabled(startButton)).toBe(false)
  })
})
