#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager@2.0.0 --dev-build=False --minimize=False
jupyter labextension install jupyter-matplotlib jupyterlab-datawidgets itkwidgets --dev-build=False --minimize=False
