name: Notebook tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run notebooks on treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: treebeardtech/treebeard@v0.1.1
        with:
          docker-username: thewtex
          docker-password: "${{ secrets.DOCKER_PASSWORD }}"
          docker-image-name: insighttoolkit/itk-elastix
          notebooks: examples/*.ipynb
