name: Notebook tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run notebooks on treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./.binder/requirements.txt
      - uses: treebeardtech/nbmake-action@v0.2
        with:
          notebooks: examples/*.ipynb
